// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/services/:id": {
    params: {
      "id": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contact" | "/services/:id" | "/sitemap.xml" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/services.$id.tsx": {
    id: "routes/services.$id";
    page: "/services/:id";
  };
  "routes/sitemap[.]xml.ts": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/services.$id": typeof import("./app/routes/services.$id.tsx");
  "routes/sitemap[.]xml": typeof import("./app/routes/sitemap[.]xml.ts");
  "routes/$": typeof import("./app/routes/$.tsx");
};